# -*- coding: utf-8 -*-
"""Python Full-Stack

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHkpDdD8xgZJN63f4a75dmYsKyqEbB-M

Date= 10/02/2026
"""

a=int(input("enter no1"))
b=int(input("enter no2"))
c=int(a)+int(b)
print('c=' ,c)

b=12.5  # variable is b
c=complex(10,20)
d=True
L1=[10,20,30]
t1=(10,20,30)
s={10,20,30}
di={'name':'ram','age':20}
str='python'
print('a=',a)  # but 'a' is not defined!
print('c=',c)
print(type(a))
print(type(str))

a,b,c=input("enter no1 = ").split()

c=int(a)+int(b)+int(c)
print('c=',c)

import random

def number_guessing_game():
    number = random.randint(1, 100)
    attempts = 0

    print("Guess a number between 1 and 100!")

    while True:
        guess = int(input("Enter your guess: "))
        attempts += 1

        if guess < number:
            print("Too low!")
        elif guess > number:
            print("Too high!")
        else:
            print(f"Yay! You guessed it in {attempts} attempts.")
            break

# Call the function
number_guessing_game()

import random

def simple_word_guessing_game():
    words = ["apple", "banana", "cherry", "orange", "grape", "mango"]
    secret_word = random.choice(words)
    attempts = 0

    print("Guess the fruit!")
    print(f"Hint: It has {len(secret_word)} letters.")

    while True:
        guess = input("Enter your guess: ").lower()
        attempts += 1

        if guess < secret_word:
            print("Your word comes alphabetically BEFORE the secret word.")
        elif guess > secret_word:
            print("Your word comes alphabetically AFTER the secret word.")
        else:
            print(f"Yay! You guessed '{secret_word}' in {attempts} attempts!")
            break

        # Additional hint
        if len(guess) != len(secret_word):
            print(f"Hint: The word has {len(secret_word)} letters.")

# Start the game
simple_word_guessing_game()

import random

def word_guessing_game():
    words = ["apple", "banana", "cherry", "date", "fig", "grape", "kiwi", "lemon", "mango", "orange"]

    secret_word = random.choice(words)
    attempts = 0

    print("Guess a word from this list:", words)
    print("Clue: Words are in alphabetical order. Try to find the secret word!")

    while True:
        guess = input("Enter your guess: ").lower()
        attempts += 1

        if guess < secret_word:
            print(f"'{guess}' comes BEFORE '{secret_word}' alphabetically!")
        elif guess > secret_word:
            print(f"'{guess}' comes AFTER '{secret_word}' alphabetically!")
        else:
            print(f"Yay! You guessed '{secret_word}' in {attempts} attempts!")
            break


word_guessing_game()

"""Date 13/02/2026

Write a Python program to create a list and perform the following operations:

Inserting an element

Removing an element

Appending an element

Displaying the length of the list

Popping an element

Clearing the list
"""

my_list = [10, 20, 30]
print("Initial List:", my_list)


my_list.insert(1, 15)
print("After Inserting 15:", my_list)

# Removing an element
my_list.remove(20)
print("After Removing 20:", my_list)

# Appending an element
my_list.append(40)
print("After Appending 40:", my_list)

# Displaying the length of the list
print("Length of the list:", len(my_list))

# Popping an element
popped_item = my_list.pop()
print("Popped Element:", popped_item)
print("List After Pop:", my_list)

my_list.clear()
print("List After Clearing:", my_list)

"""Menu Driven Program – Using Lists

Add Student Mark

Display All Marks

Update Mark

Delete Mark

Find Highest & Lowest
"""

marks = []

while True:
    print("\n1.Add  2.Display  3.Update  4.Delete  5.High/Low  6.Exit")
    ch = int(input("Choice: "))

    if ch == 1:
        marks.append(int(input("Enter mark: ")))
    elif ch == 2:
        print("Marks:", marks)
    elif ch == 3:
        old = int(input("Old mark: "))
        if old in marks:
            marks[marks.index(old)] = int(input("New mark: "))
        else:
            print("Not found!")
    elif ch == 4:
        mark = int(input("Enter mark to delete: "))
        if mark in marks:
            marks.remove(mark)
        else:
            print("Not found!")
    elif ch == 5:
        if marks:
            print("Highest:", max(marks), "Lowest:", min(marks))
        else:
            print("No marks!")
    elif ch == 6:
        break
    else:
        print("Invalid choice!")

# Dictionaries
cameras = {'canon':200, 'sony':300}
print(cameras)

cameras.update({'samsung':500})
print(cameras)

cameras['xyz'] = 1000
print(cameras)

print(cameras['sony'])
print(cameras.keys())
print(cameras.values())
print(cameras.items())

def contact_book():
    contacts = {}

    while True:
        print("\nContact Book")
        print("1. Add Contact")
        print("2. View Contacts")
        print("3. Exit")

        choice = input("Choose an option: ")

        if choice == '1':
            name = input("Enter contact name: ")
            phone = input("Enter phone number: ")
            contacts[name] = phone
            print("Contact added.")
        elif choice == '2':
            if contacts:
                print("Contacts:")
                for name, phone in contacts.items():
                    print(f"{name}: {phone}")
            else:
                print("No contacts available.m ./  ,mnbvcxz")
        elif choice == '3':
            print("Goodbye!")
            break
        else:
            print("Invalid option, please try again.")
contact_book()

i=0
for i in  range(5):
  print(i)
  i=i+1

i=0
while True:
  print(i)
  i=i+1
  if i>=5:
     break

"""Python Code (8×8 Chess Board)"""

for row in range(8):
    for col in range(8):
        if (row + col) % 2 == 0:
            print("W", end=" ")
        else:
            print("B", end=" ")
    print()   # move to next row

n = int(input("Enter size: "))

for row in range(n):
    for col in range(n):
        if (row + col) % 2 == 0:
            print("W", end=" ")
        else:
            print("B", end=" ")
    print()

"""a customer order food write a function to calculate the total bill including gst ?"""

def calculate_bill():
    prices = []

    n = int(input("Enter number of items: "))

    for i in range(n):
        price = float(input(f"Enter price of item {i+1}: "))
        prices.append(price)

    gst = float(input("Enter GST %: "))

    total = sum(prices)
    gst_amount = total * gst / 100
    final = total + gst_amount

    print("Final Bill:", final)

calculate_bill()

"""write a function to calculate simple interest ?"""

def calculate_simple_interest():
    p = float(input("Enter principal: "))
    r = float(input("Enter rate (%): "))
    t = float(input("Enter time (years): "))

    si = (p * r * t) / 100

    print("Simple Interest:", si)

calculate_simple_interest()

"""Take number of students (n)

Loop from 0 to n-1

For each student:

Take marks

Check conditions using if-elif-else

Print grade/result based on marks
"""

def student_result():
    n = int(input("Enter number of students: "))

    for i in range(n):
        marks = float(input(f"Enter marks for student {i+1}: "))

        if marks > 90:
            result = "A"
        elif marks > 75:
            result = "B"
        elif marks > 50:
            result = "C"
        elif marks > 35:
            result = "Pass"
        else:
            result = "Fail"

        print(f"Student {i+1} Result: {result}")

student_result()

"""Using recursion print the name multiple times"""

def print_name(name, n):
    if n == 0:      # base condition
        return
    print(name)
    print_name(name, n-1)   # recursive call

# user input
name = input("Enter name: ")
times = int(input("How many times: "))

print_name(name, times)

"""some of first n numbers , using recursion"""

def sum_n(n):
    if n == 1:           # base condition
        return 1
    else:
        return n + sum_n(n-1)   # recursive call

# input
n = int(input("Enter n: "))

result = sum_n(n)
print("Sum:", result)

"""Print Reverse (Using Recursion)"""

def reverse_array(arr, n):
    if n == 0:      # base condition
        return
    print(arr[n-1], end=" ")
    reverse_array(arr, n-1)

# input
arr = [1, 2, 3, 4, 5]
reverse_array(arr, len(arr))

# Base class
class Notification:
    def send_notification(self):
        print("Sending notification...")

# Instagram class
class Instagram(Notification):
    def send_notification(self):
        print("New notification from Instagram")

# WhatsApp class
class WhatsApp(Notification):
    def send_notification(self):
        print("New notification from WhatsApp")

# Email class
class Email(Notification):
    def send_notification(self):
        print("New Email received")

# Polymorphism
def notify_user(app):
    app.send_notification()

# objects
insta = Instagram()
whatsapp = WhatsApp()
email = Email()

# calling same function for different objects
notify_user(insta)
notify_user(whatsapp)
notify_user(email)

"""18/02/2026

"""

class SeatBooking:
    def __init__(self, total_seats):
        self.total_seats = total_seats
        self.current = 1

    def __iter__(self):
        return self

    def __next__(self):
        if self.current <= self.total_seats:
            seat = self.current
            self.current += 1
            return seat
        else:
            raise StopIteration


booking = SeatBooking(3)

while True:
    choice = input("Book seat? (yes/no): ").lower()

    if choice == "yes":
        try:
            seat = next(booking)
            print(f"Seat {seat} booked successfully")
        except StopIteration:
            print("No seats available")
            break
    else:
        break

"""generator"""

def numbers(n):
    for i in range(1, n+1):
        yield i

for num in numbers(5):
    print(num)

def book_seats(total):
    for seat in range(1, total+1):
        yield f"Seat {seat} booked"

booking = book_seats(3)

print(next(booking))
print(next(booking))
print(next(booking))

"""Decorator"""

def my_decorator(func):
    def wrapper(name):
        print("Before function")
        func(name)
        print("After function")
    return wrapper

@my_decorator
def greet(name):
    print("Hello", name)

greet("Megha")



"""Here's a breakdown of how the `SeatBooking` class implements the iterator protocol:

*   **`__init__(self, total_seats)`**: This is the constructor. It initializes `self.total_seats` with the maximum number of seats available and `self.current` to `1`, which will be the first seat number to be booked.

*   **`__iter__(self)`**: This method is called when an iteration is started on the object (e.g., when you call `iter(booking)` or use it in a `for` loop). For an object to be its own iterator, this method should simply return `self`.

*   **`__next__(self)`**: This method is called to get the next item in the sequence. In this class:
    *   It checks if `self.current` (the current seat number) is less than or equal to `self.total_seats`.
    *   If it is, it stores the current seat number in a variable `seat`, increments `self.current` for the next call, and returns `seat`.
    *   If `self.current` exceeds `self.total_seats`, it means all seats have been iterated through, so it raises a `StopIteration` exception. This signal tells the iterating mechanism (like a `for` loop or `while True` with `next()`) that there are no more items.

In the provided code, the `while True` loop combined with `next(booking)` effectively uses the `__next__` method until `StopIteration` is raised, indicating that no more seats are available.
"""